{% set name = "nappy" %}
{% set version = "2.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/nappy-{{ version }}.tar.gz
  sha256: b70c562131a470c17246d7b7dcf6c21597e7067534b45d1207e31252c8725926

build:
  entry_points:
    - na2nc=nappy.script.na2nc:na2nc
    - nc2na=nappy.script.nc2na:nc2na
    - nc2csv=nappy.script.nc2csv:nc2csv
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  build:
  host:
    - pip
    - setuptools
    - pypandoc
    - cf_xarray
    - cftime
    - netcdf4
    - numpy
    - python {{ python_min }}
    - scipy
    - xarray
  run:
    - cf_xarray
    - cftime
    - netcdf4
    - {{ pin_compatible('numpy') }}
    - python >={{ python_min }}
    - scipy
    - xarray

test:
  imports:
    - nappy
    - nappy.utils.compare_na
    - nappy.utils.common_utils
    - nappy.utils.text_parser
  commands:
    - pip check
    - na2nc --help
    - nc2na --help
    - nc2csv --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/cedadev/nappy
  summary: NASA Ames Processing in Python
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ReimarBauer
